### ISSUE TITLE
在OS X上的Idea上配置出现的问题

### ISSUE THREAD

**Issue by leave01** [ViceFantasyPlace/activate-power-mode#7]
由于并不熟悉OS X下的Plugin的配置，出现一些问题，作者可否简单描述一下如何在OS X的Idea下配置Plugin呢？非常感谢！

**Comment by KADO-C** [comment]
都一样的吧，哪里出现问题？我也是OS X的

**Comment by leave01** [comment]
由于实在找不到在哪里配置，第一次用Idea，网路上没能找到如何安装，还望赐教！Thank you！
<img width="1124" alt="2015-12-27 5 43 16" src="https://cloud.githubusercontent.com/assets/8081759/12009759/b95d9fc6-acc1-11e5-983e-288c5b778904.png">
<img width="1049" alt="2015-12-27 5 46 23" src="https://cloud.githubusercontent.com/assets/8081759/12009760/c52f4e8a-acc1-11e5-8064-bde7c8132c1a.png">

**Comment by KADO-C** [comment]
如果只是安装插件的话，只要下载那个jar包就可以了，然后选Install pliugin form disk, 然后找到那个jar就可以了。
－－jar包链接：https://github.com/ViceFantasyPlace/activate-power-mode/releases
如果是像下载那个源码自己编译的话，我看你上面的是不是还没装IDEA的SDK
![image](https://cloud.githubusercontent.com/assets/9715438/12009815/214f2102-acc4-11e5-8ddd-8c929f11856a.png)

**Comment by leave01** [comment]
非常感谢，刚才已经成功安装了。
ps.Idea的目录浏览框不枚举目录下的文件，还以为不支持，手动加activate-power-mode-v0.0.6.jar后好了。
再次感谢！

**Comment by succour** [comment]
Plugin 'com.jiyuanime.ActivatePowerModeApplicationPlugin' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

com.intellij.diagnostic.PluginException: com/jiyuanime/ActivatePowerModeApplicationPlugin : Unsupported major.minor version 52.0 [Plugin: com.jiyuanime.ActivatePowerModeApplicationPlugin]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/jiyuanime/ActivatePowerModeApplicationPlugin : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 30 more


MAC版的IDEA装完之后启动不了...报错信息如上,咋弄啊...

**Comment by KADO-C** [comment]
是不是你jdk版本不一致啊？开发时的版本和运行时的版本不一致 会报 Unsupported major.minor version 52.0

**Comment by KADO-C** [comment]
https://github.com/jshiell/checkstyle-idea/issues/142

**Comment by succour** [comment]
搞定了~~~多谢多谢

**Comment by CatherineLiyuankun** [comment]
Platform: mac os x
IntelliJ Version: 14.1.4 Ultimate
JDK 7

是jdk版本不一致的问题吗，应该用哪个版本的可以？@KADO-C

IDEA的SDK 应该去哪下？

报错：

Plugin 'com.jiyuanime.ActivatePowerModeApplicationPlugin' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

com.intellij.diagnostic.PluginException: com/jiyuanime/ActivatePowerModeApplicationPlugin : Unsupported major.minor version 52.0 [Plugin: com.jiyuanime.ActivatePowerModeApplicationPlugin]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:274)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.UnsupportedClassVersionError: com/jiyuanime/ActivatePowerModeApplicationPlugin : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 30 more

**Comment by hentai-mew** [comment]
有可能是你的JDK版本问题。不过也没关系，你可以把源码导入自己编译并打包一个jar，再安装自己的，就可以正常使用了。

**Comment by KADO-C** [comment]
JDK1.7或者JDK1.8都可以的，你这个错误应该是OS X指定默认的JDK版本跟你IDEA设置的JDK版本不一致, 你安装完JDK1.7之后有没有自己手动配下环境变量，我记得我当时OS X装JDK的时候也是，安装成功了，但是 java -version 还是OS X本身默认安装的JDK1.6，后来手动配环境变量之后就可以了 @CatherineLiyuankun

**Comment by CatherineLiyuankun** [comment]
@hentai-mew    恩，又安装了jdk1.8，可以用了

@KADO-C 我检查了下，是1.7的，我又安装了jdk1.8，可以用了
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by KADO-C** [comment]
那就OK了😊

**Comment by CatherineLiyuankun** [comment]
写了篇博客：activate-power-mode 写代码的时候体验狂拽酷炫的效果 （IDEA版安装过程及问题）http://blog.csdn.net/muzilanlan/article/details/50513078

给新手看吧，省的琢磨半天。。。

**Comment by xirtam-ch** [comment]
@KADO-C 
能否发一个去掉晃动，只有粒子的版本编译成jar发给我。。。多谢
xirtam.zhang@gmail.com

**Comment by KADO-C** [comment]
@xirtam-ch 直接在Windows -> activate-power-mode -> shake 把勾去掉就没有了晃动的了

**Comment by xirtam-ch** [comment]
@KADO-C 噢，找到了，谢谢

**Comment by xyqfer** [comment]
请教下有办法在 Webstorm 上安装吗？

**Comment by zhimajiang** [comment]
@xyqfer 我刚才下载个webstorm试下装，表示可以，你那边具体有什么错误？

**Comment by xyqfer** [comment]
@zhimajiang 感谢回复~

遇到的错误跟上面几位的类似：
```
Plugin 'com.jiyuanime.ActivatePowerModeApplicationPlugin' failed to initialize and will be disabled.  Please restart WebStorm.

com.intellij.diagnostic.PluginException: com/jiyuanime/ActivatePowerModeApplicationPlugin : Unsupported major.minor version 52.0 [Plugin: com.jiyuanime.ActivatePowerModeApplicationPlugin]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:274)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.UnsupportedClassVersionError: com/jiyuanime/ActivatePowerModeApplicationPlugin : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 30 more
```

- OS X 10.11 
- Webstorm 10.0.4
```
<key>JVMVersion</key>
<string>1.6*,1.7+</string>
```

```
- java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```
- Java 8 好像是装了。。
![qq20160318-0](https://cloud.githubusercontent.com/assets/5186792/13872796/dea760a4-ed27-11e5-9dee-15e78d1c3005.png)

**Comment by KADO-C** [comment]
@xyqfer 应该要手动配置一下jdk路径，还有在idea里面指定一些跟系统当前环境变量一样的jdk版本, [楼上CatherineLiyuankun写的博客有说哦](#issuecomment-171298095)

**Comment by xyqfer** [comment]
@KADO-C 感谢回复~
我用的是 Webstorm，找了一圈似乎没找着 WebStorm 哪里修改 jdk 版本的，还请指教。谢谢~

**Comment by KADO-C** [comment]
@xyqfer 我下载了web storm，安装过运行也没问题，请问你是安装插件的jar包么，你试一下 java -version  看一下你当前系统默认的是那个jdk版本

**Comment by xyqfer** [comment]
@KADO-C 谢谢~
我是通过插件的 jar 包安装的

```
- java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by KADO-C** [comment]
@xyqfer 试一下配置一下环境变量，把jdk1.8配置为系统默认版本

**Comment by xyqfer** [comment]
@KADO-C 感谢~已解决
