### ISSUE TITLE
Pycharm安装完插件后重启报错

### ISSUE THREAD

**Issue by qianlinyi** [ViceFantasyPlace/activate-power-mode#88]
两台电脑的pycharm安装完插件后重启都报这个错，找了半天也不知道哪里有问题/(ㄒoㄒ)/~~

Plugin 'com.jiyuanime.ActivatePowerModeApplicationPlugin' failed to initialize and will be disabled. Please restart PyCharm.

java.lang.ClassNotFoundException: com.jiyuanime.ActivatePowerModeApplicationPlugin
             PluginClassLoader(plugin=PluginDescriptor(name=activate-power-mode, id=com.jiyuanime.ActivatePowerModeApplicationPlugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2021.3\plugins\activate-power-mode_v0.1.8.jar, version=0.1.8, package=null, isBundled=false), packagePrefix=null, instanceId=19, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:437)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:372)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:56)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:253)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:79)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:112)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:67)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.y.Y(y.java:96)
    at com.intellij.ide.Y.S.A.Y(A.java:122)
    at com.intellij.ide.Y.S.p1.u(p1.java:166)
    at com.intellij.ide.Y.S.p9.R(p9.java:136)
    at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
    at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
    at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.ide.Y.S.p9.k(p9.java:136)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:83)
    at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:286)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by jadehh** [comment]
+1

**Comment by qe-present** [comment]
question there（path=~\AppData\Roaming\JetBrains\PyCharm2021.3\plugins\activate-power-mode_v0.1.8.jar）

**Comment by Serendipity-LJ** [comment]
+1 请问您解决了吗？

**Comment by Serendipity-LJ** [comment]
> 两台电脑的pycharm安装完插件后重启都报这个错，找了半天也不知道哪里有问题/(ㄒoㄒ)/~~
> 
> Plugin 'com.jiyuanime.ActivatePowerModeApplicationPlugin' failed to initialize and will be disabled. Please restart PyCharm.
> 
> java.lang.ClassNotFoundException: com.jiyuanime.ActivatePowerModeApplicationPlugin PluginClassLoader(plugin=PluginDescriptor(name=activate-power-mode, id=com.jiyuanime.ActivatePowerModeApplicationPlugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2021.3\plugins\activate-power-mode_v0.1.8.jar, version=0.1.8, package=null, isBundled=false), packagePrefix=null, instanceId=19, state=active) at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:437) at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:372) at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:56) at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:253) at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63) at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:79) at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt) at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:77) at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:112) at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118) at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246) at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143) at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:67) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.intellij.idea.y.Y(y.java:96) at com.intellij.ide.Y.S.A.Y(A.java:122) at com.intellij.ide.Y.S.p1.u(p1.java:166) at com.intellij.ide.Y.S.p9.R(p9.java:136) at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815) at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799) at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.intellij.ide.Y.S.p9.k(p9.java:136) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.intellij.idea.MainImpl.start(MainImpl.java:83) at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:286) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

我也是 怎么解决呀

**Comment by qianlinyi** [comment]
> +1 请问您解决了吗？

不知道是不是原来的插件有问题，可以用另一个active-power-mode-x

**Comment by Serendipity-LJ** [comment]
> > +1 请问您解决了吗？
> 
> 不知道是不是原来的插件有问题，可以用另一个active-power-mode-x

可以了哎！应该是这个插件不更了！谢谢~

**Comment by Kyu** [comment]
Good fork: https://github.com/SinarPandora/activate-power-mode
